# Generated by Django 6.0.4 on 2026-04-27 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('current_stage', models.CharField(choices=[('PROJECT_REGISTERED', 'Project Registered'), ('REQUIREMENTS_COLLECTED', 'Requirements Collected'), ('SITE_VISIT', 'Site Visit'), ('CONCEPT_DESIGN', 'Concept Design'), ('CLIENT_REVIEW', 'Client Review'), ('REVISIONS', 'Revisions'), ('FINAL_DESIGN', 'Final Design'), ('DRAWINGS_PREPARATION', 'Drawings Preparation'), ('MUNICIPALITY_SUBMISSION', 'Municipality Submission'), ('APPROVAL_STAGE', 'Approval Stage'), ('SUPERVISION_EXECUTION', 'Supervision / Execution'), ('COMPLETED', 'Completed')], default='PROJECT_REGISTERED', max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('WAITING_CLIENT', 'Waiting Client'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='engineers.engineer')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client')),
            ],
        ),
    ]
