# Generated by Django 6.0.4 on 2026-04-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0002_engineer_department'),
        ('projects', '0003_projectcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_engineer',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_engineers',
            field=models.ManyToManyField(blank=True, related_name='projects', to='engineers.engineer'),
        ),
    ]
