# Generated by Django 6.0.4 on 2026-04-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='department',
            field=models.CharField(blank=True, choices=[('INTERIOR_DESIGNER', 'Interior Designer'), ('MECHANICAL_ENGINEER', 'Mechanical Engineer'), ('ELECTRICAL_ENGINEER', 'Electrical Engineer'), ('SUPERVISOR', 'Supervisor'), ('ARCHITECT', 'Architect')], max_length=50, null=True),
        ),
    ]
